"""fechas_envio_entrega

Revision ID: 1c533bbe8d78
Revises: 5fb84efa383f
Create Date: 2026-06-28 16:54:30.548874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c533bbe8d78'
down_revision = '5fb84efa383f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_envio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_entrega', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('fecha_entrega')
        batch_op.drop_column('fecha_envio')

    # ### end Alembic commands ###
