"""vinculo usuario-cliente

Revision ID: 5fb84efa383f
Revises: 96c674cd2325
Create Date: 2026-06-24 16:17:53.473659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb84efa383f'
down_revision = '96c674cd2325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_clientes_usuario_id', ['usuario_id'])
        batch_op.create_foreign_key('fk_clientes_usuarios', 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('correo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_constraint('fk_clientes_usuarios', type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
