"""agregar campos de progreso de simulacion

Revision ID: 8099aaaee574
Revises: f117a6ddb869
Create Date: 2026-06-29 08:27:56.391894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8099aaaee574'
down_revision = 'f117a6ddb869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progreso_simulacion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('simulacion_activa', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('simulacion_activa')
        batch_op.drop_column('progreso_simulacion')

    # ### end Alembic commands ###